title: Fertility Clinic
email: info@yourclinic.com
description: Compassionate and expert fertility care in Cyprus.
baseurl: "Fertility-Clinic-Website"
url: ""

# Theme settings
markdown: kramdown
permalink: pretty

# Navigation
header_pages:
  - about.md
  - consultation.md
  - contact.md
